"""
Company Universe definitions for the 20-Company Research Beta.
Defines metadata, tickers, sector packs, and classification attributes (Layer A and Layer B).
"""

from typing import List, Dict, Any

COMPANIES_20: List[Dict[str, Any]] = [
    # -------------------------------------------------------------------------
    # Pack 1: Banks and NBFCs (5 companies)
    # -------------------------------------------------------------------------
    {
        "symbol": "HDFCBANK.NS",
        "ticker": "HDFCBANK",
        "legal_name": "HDFC Bank Limited",
        "common_name": "HDFC Bank",
        "isin": "INE040A01034",
        "bse_code": "500180",
        "sector": "Banks & NBFCs",
        "subsector": "Private Sector Bank",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        # Layer B Attributes
        "financial_nature": "Financial",
        "lifecycle": "Mature",
        "business_model": "Lending & Financial Services",
        "asset_intensity": "Financial Balance Sheet",
        "structure_type": "Simple",
        "regulatory_model": "Regulated",
        "primary_methods": ["P/B", "Residual Income", "DDM"],
        "veto_methods": ["EV/EBITDA", "EV/EBIT", "FCFF DCF"],
    },
    {
        "symbol": "ICICIBANK.NS",
        "ticker": "ICICIBANK",
        "legal_name": "ICICI Bank Limited",
        "common_name": "ICICI Bank",
        "isin": "INE090A01021",
        "bse_code": "532174",
        "sector": "Banks & NBFCs",
        "subsector": "Private Sector Bank",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Financial",
        "lifecycle": "Mature",
        "business_model": "Lending & Financial Services",
        "asset_intensity": "Financial Balance Sheet",
        "structure_type": "Simple",
        "regulatory_model": "Regulated",
        "primary_methods": ["P/B", "Residual Income", "DDM"],
        "veto_methods": ["EV/EBITDA", "EV/EBIT", "FCFF DCF"],
    },
    {
        "symbol": "SBIN.NS",
        "ticker": "SBIN",
        "legal_name": "State Bank of India",
        "common_name": "SBI",
        "isin": "INE062A01020",
        "bse_code": "500112",
        "sector": "Banks & NBFCs",
        "subsector": "Public Sector Bank",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Financial",
        "lifecycle": "Mature",
        "business_model": "Lending & Financial Services",
        "asset_intensity": "Financial Balance Sheet",
        "structure_type": "Simple",
        "regulatory_model": "Regulated",
        "primary_methods": ["P/B", "Residual Income", "DDM"],
        "veto_methods": ["EV/EBITDA", "EV/EBIT", "FCFF DCF"],
    },
    {
        "symbol": "BAJFINANCE.NS",
        "ticker": "BAJFINANCE",
        "legal_name": "Bajaj Finance Limited",
        "common_name": "Bajaj Finance",
        "isin": "INE296A01024",
        "bse_code": "500034",
        "sector": "Banks & NBFCs",
        "subsector": "NBFC",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Financial",
        "lifecycle": "Growth",
        "business_model": "Retail & Commercial Lending",
        "asset_intensity": "Financial Balance Sheet",
        "structure_type": "Simple",
        "regulatory_model": "Regulated",
        "primary_methods": ["P/B", "P/E", "Residual Income"],
        "veto_methods": ["EV/EBITDA", "EV/EBIT", "FCFF DCF"],
    },
    {
        "symbol": "SHRIRAMFIN.NS",
        "ticker": "SHRIRAMFIN",
        "legal_name": "Shriram Finance Limited",
        "common_name": "Shriram Finance",
        "isin": "INE721A01013",
        "bse_code": "511218",
        "sector": "Banks & NBFCs",
        "subsector": "NBFC - Commercial Vehicles",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Financial",
        "lifecycle": "Mature",
        "business_model": "Asset Financing",
        "asset_intensity": "Financial Balance Sheet",
        "structure_type": "Simple",
        "regulatory_model": "Regulated",
        "primary_methods": ["P/B", "P/E", "Residual Income"],
        "veto_methods": ["EV/EBITDA", "EV/EBIT", "FCFF DCF"],
    },

    # -------------------------------------------------------------------------
    # Pack 2: IT Services (3 companies)
    # -------------------------------------------------------------------------
    {
        "symbol": "TCS.NS",
        "ticker": "TCS",
        "legal_name": "Tata Consultancy Services Limited",
        "common_name": "TCS",
        "isin": "INE467B01029",
        "bse_code": "532540",
        "sector": "IT Services",
        "subsector": "IT Consulting & Services",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Recurring / Service-based",
        "asset_intensity": "Asset-light",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBIT"],
        "veto_methods": ["P/B", "Residual Income"],
    },
    {
        "symbol": "INFY.NS",
        "ticker": "INFY",
        "legal_name": "Infosys Limited",
        "common_name": "Infosys",
        "isin": "INE009A01021",
        "bse_code": "500209",
        "sector": "IT Services",
        "subsector": "IT Consulting & Services",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Recurring / Service-based",
        "asset_intensity": "Asset-light",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBIT"],
        "veto_methods": ["P/B", "Residual Income"],
    },
    {
        "symbol": "HCLTECH.NS",
        "ticker": "HCLTECH",
        "legal_name": "HCL Technologies Limited",
        "common_name": "HCLTech",
        "isin": "INE860A01027",
        "bse_code": "532281",
        "sector": "IT Services",
        "subsector": "IT Consulting & Services",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Recurring / Service-based",
        "asset_intensity": "Asset-light",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBIT"],
        "veto_methods": ["P/B", "Residual Income"],
    },

    # -------------------------------------------------------------------------
    # Pack 3: FMCG / Consumer (3 companies)
    # -------------------------------------------------------------------------
    {
        "symbol": "HINDUNILVR.NS",
        "ticker": "HINDUNILVR",
        "legal_name": "Hindustan Unilever Limited",
        "common_name": "Hindustan Unilever",
        "isin": "INE030A01027",
        "bse_code": "500696",
        "sector": "FMCG / Consumer",
        "subsector": "Household & Personal Care",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Branded Consumer Goods",
        "asset_intensity": "Asset-light",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },
    {
        "symbol": "ITC.NS",
        "ticker": "ITC",
        "legal_name": "ITC Limited",
        "common_name": "ITC",
        "isin": "INE154A01025",
        "bse_code": "500875",
        "sector": "FMCG / Consumer",
        "subsector": "Diversified Consumer Goods",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Branded Consumer / Conglomerate",
        "asset_intensity": "Mixed",
        "structure_type": "SOTP candidate",
        "regulatory_model": "Regulated (Excise / Tax)",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },
    {
        "symbol": "NESTLEIND.NS",
        "ticker": "NESTLEIND",
        "legal_name": "Nestle India Limited",
        "common_name": "Nestlé India",
        "isin": "INE239A01024",
        "bse_code": "500790",
        "sector": "FMCG / Consumer",
        "subsector": "Packaged Foods",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Branded Consumer Goods",
        "asset_intensity": "Asset-light",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },

    # -------------------------------------------------------------------------
    # Pack 4: Manufacturing / Auto (4 companies)
    # -------------------------------------------------------------------------
    {
        "symbol": "MARUTI.NS",
        "ticker": "MARUTI",
        "legal_name": "Maruti Suzuki India Limited",
        "common_name": "Maruti Suzuki",
        "isin": "INE585B01010",
        "bse_code": "532500",
        "sector": "Manufacturing / Auto",
        "subsector": "Passenger Vehicles",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Cyclical / Mature",
        "business_model": "Original Equipment Manufacturer (OEM)",
        "asset_intensity": "Asset-heavy",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },
    {
        "symbol": "M&M.NS",
        "ticker": "M&M",
        "legal_name": "Mahindra & Mahindra Limited",
        "common_name": "Mahindra & Mahindra",
        "isin": "INE101A01026",
        "bse_code": "500520",
        "sector": "Manufacturing / Auto",
        "subsector": "Automotive & Farm Equipment",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Cyclical / Growth",
        "business_model": "OEM & Conglomerate",
        "asset_intensity": "Asset-heavy",
        "structure_type": "SOTP candidate",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },
    {
        "symbol": "EICHERMOT.NS",
        "ticker": "EICHERMOT",
        "legal_name": "Eicher Motors Limited",
        "common_name": "Eicher Motors",
        "isin": "INE066A01021",
        "bse_code": "505200",
        "sector": "Manufacturing / Auto",
        "subsector": "Two Wheelers & Commercial Vehicles",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature / Growth",
        "business_model": "Premium OEM",
        "asset_intensity": "Mixed",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },
    {
        "symbol": "BAJAJ-AUTO.NS",
        "ticker": "BAJAJ-AUTO",
        "legal_name": "Bajaj Auto Limited",
        "common_name": "Bajaj Auto",
        "isin": "INE917I01010",
        "bse_code": "532977",
        "sector": "Manufacturing / Auto",
        "subsector": "Automotive - 2&3 Wheelers",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "OEM Manufacturing",
        "asset_intensity": "Asset-heavy",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },

    # -------------------------------------------------------------------------
    # Pack 5: Infrastructure / EPC (2 companies)
    # -------------------------------------------------------------------------
    {
        "symbol": "LT.NS",
        "ticker": "LT",
        "legal_name": "Larsen & Toubro Limited",
        "common_name": "Larsen & Toubro",
        "isin": "INE018A01030",
        "bse_code": "500510",
        "sector": "Infrastructure / EPC",
        "subsector": "Engineering & Construction",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Project & EPC",
        "asset_intensity": "Mixed / Heavy",
        "structure_type": "SOTP candidate",
        "regulatory_model": "Market-priced + Concessions",
        "primary_methods": ["FCFF DCF", "EV/EBITDA", "P/E"],
        "veto_methods": ["Residual Income"],
    },
    {
        "symbol": "KEC.NS",
        "ticker": "KEC",
        "legal_name": "KEC International Limited",
        "common_name": "KEC International",
        "isin": "INE855B01025",
        "bse_code": "532714",
        "sector": "Infrastructure / EPC",
        "subsector": "Power T&D & EPC Infrastructure",
        "market_cap_class": "Mid Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Growth",
        "business_model": "Project / Contracting",
        "asset_intensity": "Asset-heavy",
        "structure_type": "Simple",
        "regulatory_model": "Market-priced",
        "primary_methods": ["FCFF DCF", "EV/EBITDA", "P/E"],
        "veto_methods": ["Residual Income"],
    },

    # -------------------------------------------------------------------------
    # Pack 6: Pharmaceuticals (3 companies)
    # -------------------------------------------------------------------------
    {
        "symbol": "SUNPHARMA.NS",
        "ticker": "SUNPHARMA",
        "legal_name": "Sun Pharmaceutical Industries Limited",
        "common_name": "Sun Pharma",
        "isin": "INE044A01036",
        "bse_code": "524715",
        "sector": "Pharmaceuticals",
        "subsector": "Formulations & Specialty Pharma",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Branded & Specialty Generics",
        "asset_intensity": "Asset-light",
        "structure_type": "Simple",
        "regulatory_model": "Regulated (USFDA/US Market)",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },
    {
        "symbol": "DRREDDY.NS",
        "ticker": "DRREDDY",
        "legal_name": "Dr. Reddy's Laboratories Limited",
        "common_name": "Dr. Reddy's",
        "isin": "INE089A01023",
        "bse_code": "500124",
        "sector": "Pharmaceuticals",
        "subsector": "Generics & Biosimilars",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Generics & Global Pharma",
        "asset_intensity": "Asset-light",
        "structure_type": "Simple",
        "regulatory_model": "Regulated",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },
    {
        "symbol": "CIPLA.NS",
        "ticker": "CIPLA",
        "legal_name": "Cipla Limited",
        "common_name": "Cipla",
        "isin": "INE059A01026",
        "bse_code": "500087",
        "sector": "Pharmaceuticals",
        "subsector": "Respiratory & Domestic Generics",
        "market_cap_class": "Large Cap",
        "listing_status": "Listed",
        "financial_nature": "Non-financial",
        "lifecycle": "Mature",
        "business_model": "Branded Generics",
        "asset_intensity": "Asset-light",
        "structure_type": "Simple",
        "regulatory_model": "Regulated",
        "primary_methods": ["FCFF DCF", "P/E", "EV/EBITDA"],
        "veto_methods": ["Residual Income"],
    },
]

def get_all_symbols() -> List[str]:
    return [c["symbol"] for c in COMPANIES_20]

def get_company_by_symbol(symbol: str) -> Dict[str, Any]:
    for c in COMPANIES_20:
        if c["symbol"].upper() == symbol.upper() or c["ticker"].upper() == symbol.upper():
            return c
    return {}
